# Generated by Django 2.1.7 on 2019-03-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_hall'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('hall', models.ManyToManyField(related_name='halls', to='webapp.Hall', verbose_name='Зал')),
            ],
        ),
        migrations.AlterField(
            model_name='movie',
            name='categories',
            field=models.ManyToManyField(related_name='categories', to='webapp.Category', verbose_name='Категория'),
        ),
    ]
