# Generated by Django 2.1.7 on 2019-03-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
