# Generated by Django 2.1.7 on 2019-03-05 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20190304_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='hall',
        ),
        migrations.AddField(
            model_name='seat',
            name='hall',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='halls', to='webapp.Hall'),
        ),
        migrations.RemoveField(
            model_name='show',
            name='hall',
        ),
        migrations.AddField(
            model_name='show',
            name='hall',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='show_halls', to='webapp.Hall'),
        ),
        migrations.RemoveField(
            model_name='show',
            name='movie',
        ),
        migrations.AddField(
            model_name='show',
            name='movie',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='movies', to='webapp.Movie'),
        ),
    ]
