# Generated by Django 2.1.7 on 2019-03-07 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20190307_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='discount',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='discounts', to='webapp.Discount'),
        ),
    ]
